### ISSUE TITLE
Add a todo checklist post install

### ISSUE THREAD

**Issue by jaebradley** [jaebradley/fruit#20]
Like
- [ ] Add a license
- [ ] Add keywords to package.json
- [ ] Create GitHub repository
- [ ] Run `semantic-release-cli setup` command
etc
